### ISSUE TITLE
[Enhancement] Be able to add other Non-Selectable Dates as "disabled or holydays"

### ISSUE THREAD

**Issue by ronycohen** [DenniLa2/ionic-datepicker#1]
Hello,

Currently we wan add some Selectable holydays : (with a red dot) 
![image](https://cloud.githubusercontent.com/assets/7273443/11335450/8e63b832-91dc-11e5-8e7f-904aff6fd1bc.png)

Or we can add some Non-Selectable Disabled Dates : (with a grey background)
![image](https://cloud.githubusercontent.com/assets/7273443/11335470/c0695fc6-91dc-11e5-99ca-d34f62f81c74.png)

Is it easy to enhance, and possible to add other selectabled dates ?
I'm thinking of birthdays and other dates which in a context could make sense ?

Like the selected dates : 
![image](https://cloud.githubusercontent.com/assets/7273443/11335506/f9d1dce8-91dc-11e5-8edf-c72e5c9ce5b6.png)

But with a different color ?

![image](https://cloud.githubusercontent.com/assets/7273443/11335391/2e55cb42-91dc-11e5-8dff-f6a9f718a36c.png)

Thank you very much for your work !

**Comment by DenniLa2** [comment]
How can i show another events? Round used by today, top-left red dot - holidays, square or circle (background) - disabled / selected dates. Where can located blue dots? Blue dots as sample. I can add any quantity of arrays. But i limited my fantasy about location of new points.

**Comment by ronycohen** [comment]
Hi Denni, 

Yes, why not just define background colors ? (Like the selected dates) and when we select the date, it get the red color you defined for the selected dates.

**Comment by ronycohen** [comment]
Or just a background color like the disabled dates (the square).

**Comment by ronycohen** [comment]
The disabled dates can also be with opacity: 0.5. this way
you can use the square background colors for other purpose :)

**Comment by DenniLa2** [comment]
Concept:
Selected - is main calendar.
Disabled - second.
Holidays and other - third.
![cal-things](https://cloud.githubusercontent.com/assets/9018493/11349585/9a8c3c34-9235-11e5-9006-e6e6537d90d5.jpg)
1. holidays
2-6 (2-8) - other future named / numbered calendars. Each of them has own place. But colors from external classes.

**Comment by DenniLa2** [comment]
Added 7 calendars with external classes - colors of dots.

Rate pls http://market.ionic.io/plugins/ionic-multi-date-picker =)

**Comment by DenniLa2** [comment]
Rate pls.

**Comment by ronycohen** [comment]
OK :)

**Comment by ronycohen** [comment]
Great ! it's very nice !!!
