### ISSUE TITLE
[Enhancement] Weekly Checkin

### ISSUE THREAD

**Issue by ronycohen** [DenniLa2/ionic-datepicker#2]
Hello, 

Here is a new idea of enhancement : 
The Weekly Checkin.

Currently we could implement a weekly checkin by selecting all of the day of the week.
But this pattern is hard to manage in an application context : 
Because a week selection doesn't always mean each days of the week.

The idea is to display / save the week-Number .
![image](https://cloud.githubusercontent.com/assets/7273443/11364557/637ff64c-92a1-11e5-9df0-f63e7ebf39cd.png)

**Comment by DenniLa2** [comment]
This is a good idea. Ok, I'll think about it.

**Comment by ronycohen** [comment]
Thank you Denni :)

**Comment by ronycohen** [comment]
For now I'm selecting the whole week as selected Dates, then I detect when every days of a week are selected. in order to not save 7 values.

**Comment by DenniLa2** [comment]
Now I'm busy, but I thought about it. I think that the choice of several dates for one-touch would be more correct.

**Comment by ronycohen** [comment]
Yes, sorry my english vocabulary is not good sometimes :).
#1 I select a day (one-touch)
#2 I detect which Week
#3  I detect which days of week
#4 I force select all the days of the week.

Then with the DB currently I do : 

#1 if all of the days of the week are selected, 
#2 delete days of the week
#3 save the number of the week

It's an unefficient workaround, ^^

**Comment by DenniLa2** [comment]
Complete added 'select by week' toggle.

**Comment by ronycohen** [comment]
Really ? 
Let me try !! Thank you Denni !

**Comment by DenniLa2** [comment]
=)

**Comment by ronycohen** [comment]
Denni, can you please tell me how to use it ?
I didn't find information about it...

**Comment by ronycohen** [comment]
tglSelectByWeekShow: true, // true | false (default)
      isSelectByWeek: true, // true (default) | false

**Comment by ronycohen** [comment]
OK It's working very well !!
I'll keep my function to save the Week instead of 7 days !

**Comment by ronycohen** [comment]
A feedback : there is an inversion of selection, when some days are already selected.
Probably the best is to select or unselect all of the days : 

I select 2 dates : 
![image](https://cloud.githubusercontent.com/assets/7273443/11536268/f18068d8-9917-11e5-9f2b-77f001e9c3fa.png)

after a check of the same week : 
![image](https://cloud.githubusercontent.com/assets/7273443/11536280/0a9fcf7a-9918-11e5-8c36-659504e4348d.png)

**Comment by DenniLa2** [comment]
Yes. I love inversion and recursion =). Ok. I write trigger and option "isSelectByWeekInversion". Coming soon :^)

**Comment by ronycohen** [comment]
ahahahah ok great :dancer:

**Comment by DenniLa2** [comment]
selectByWeekMode: 'INVERSION' (default), 'NORMAL'.

**Comment by ronycohen** [comment]
Thank you !!
