### ISSUE TITLE
[Enhancement] a no-modal version.

### ISSUE THREAD

**Issue by ronycohen** [DenniLa2/ionic-datepicker#3]
Hello,

Here is a new idea of enhancement.
Be able to use the the calendar as a non modal display.

**Comment by DenniLa2** [comment]
Hello, 
You can use popup mode.

**Comment by ronycohen** [comment]
I was talking about the calendar accessible in the web-view without getting a Modal or a Popup.

**Comment by DenniLa2** [comment]
As element? Inside other content?

**Comment by ronycohen** [comment]
Yes :)

**Comment by DenniLa2** [comment]
This is interesting idea. It takes time to think.

**Comment by ronycohen** [comment]
Yes Definitely.
Denni thank you for this amazing Calendar.

**Comment by DenniLa2** [comment]
I don`t know easy way to do this. Feel free to pull request.

**Comment by ronycohen** [comment]
Hi Denni, 
What are the difficulties concerning thie enhancement ?

Is it because of the css management ?

**Comment by DenniLa2** [comment]
Hi Ronyrun,
It is because need to write another directive.

**Comment by ronycohen** [comment]
AH ok I understand what you mean.
Unfortunately...  I don't have your coding level for now.... 
then I understand this can be painfull.

Look at the calendar of the "Doodle" smartphone application
When they ask you to select a Date, you have a calendar of every months in a list.
It's very nice, and I that's why I got this idea of a calendar as element.

![image](https://cloud.githubusercontent.com/assets/7273443/11634075/d2f63f3c-9d0e-11e5-9b1f-1b5dcbf98390.png)

**Comment by DenniLa2** [comment]
What is name of "Doodle smartphone application"? I find only games =). Doodle jump,  etc... I can do vertical calendar slider, but very few space on the screen for additional feature.

**Comment by ronycohen** [comment]
https://play.google.com/store/apps/details?id=com.doodle.android

https://itunes.apple.com/us/app/doodle-schedule-maker/id938182547?mt=8

**Comment by DenniLa2** [comment]
Interesting solution. But Doodle date-selector has only calendar and start-date is now. My calendar has many features: buttons, error-field, date convention field, select-by-week toggle =) and default not has start-date.
I write my date-picker because my client wanted calendar with "select many dates" feature and another date-picker not have this feature.

**Comment by ronycohen** [comment]
Yes your calendar is amazing :)

for a "select many dates" calendar like yours, would't be better to slide for changing the month ?
That's why I displayed this example of a list of "months" multidates calendar. this way you can select many daytes with slides from a month to another.

In particular the "doodle" exemple is a vertical slide :)
